<?php

return [
    'Settings'                                                                                                                                                                                                      => 'Einstellungen',
    'Info'                                                                                                                                                                                                          => 'Info',
    'Exitintent Settings'                                                                                                                                                                                           => 'Exitintent Einstellungen',
    'Pages'                                                                                                                                                                                                         => 'Seiten',
    'HTML'                                                                                                                                                                                                          => 'HTML',
    'Sensitivity'                                                                                                                                                                                                   => 'Sensibilität',
    'Aggressive'                                                                                                                                                                                                    => 'Aggressiv',
    'Timer'                                                                                                                                                                                                         => 'Timer',
    'Cookie Lifetime'                                                                                                                                                                                               => 'Cookie-Lebensdauer',
    'Days'                                                                                                                                                                                                          => 'Tage',
    'Cookie Name'                                                                                                                                                                                                   => 'Cookie-Name',
    'Sitewide Cookie'                                                                                                                                                                                               => 'Cookie seitenweit',
    'Save'                                                                                                                                                                                                          => 'Speichern',
    'Exitintent Info'                                                                                                                                                                                               => 'Exitintent Info',
    'Getting help'                                                                                                                                                                                                  => 'Hilfe erhalten',
    'You have problems using this extension? Join the Pagekit community forum.'                                                                                                                                     => 'Probleme bei der Verwendung dieser Erweiterung? Im Pagekit-Forum findet sich bestimmt eine Lösung.',
    'Donate'                                                                                                                                                                                                        => 'Spenden',
    'Do you like my extensions? They are free. Of course I would like to get a donation, so if you want to, please open the donate link. You may find three possibilities to donate: PayPal, Patreon and Coinhive.' => 'Ist diese Erweiterung hilfreich? Sie ist kostenfrei! Natürlich freue ich mich aber über eine kleine Spende. Der Spenden-Link öffnet eine neue Seite, die drei mögliche Spendenmöglichkeiten zeigt: PayPal, Patreon und Coinhive.',
];